# -*- coding: utf-8 -*-
"""Dashboard precio del Café.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G6N6Gc8IAyaACq8g-YwANSDrCIsZH6QX

#Integrantes:
##Sebastian Benavides Ortega
##Leidy Dahiana Hoyos Cardona
##Daniel Rúa Castrillón

# **Código consolidado**
"""

!pip install dash==3.2.0
!pip install -q dash-bootstrap-components

import random as rnd
import pandas as pd
import numpy as np
from google.colab import files
import plotly.express as px
from dash import callback_context


from dash import Dash, dcc, html, Input, Output, State
import dash_bootstrap_components as dbc
import plotly.express as px
import numpy as np
import pandas as pd

# Realizamos una lista con los años que analizaremos
año = ['2006', '2006', '2006', '2006', '2006', '2006', '2006', '2006', '2006', '2006', '2006', '2006', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007', '2007','2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2008', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009', '2009','2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010', '2010','2011', '2011', '2011', '2011', '2011', '2011', '2011', '2011', '2011', '2011', '2011', '2011','2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012', '2012','2013', '2013', '2013', '2013', '2013', '2013', '2013', '2013', '2013', '2013', '2013', '2013','2014', '2014', '2014', '2014', '2014', '2014', '2014', '2014', '2014', '2014', '2014', '2014','2015', '2015', '2015', '2015', '2015', '2015', '2015', '2015', '2015', '2015', '2015', '2015','2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016', '2016','2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017', '2017','2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018', '2018','2019', '2019', '2019', '2019', '2019', '2019', '2019', '2019', '2019', '2019', '2019', '2019','2020', '2020', '2020', '2020', '2020', '2020', '2020', '2020', '2020', '2020', '2020', '2020','2021', '2021', '2021', '2021', '2021', '2021', '2021', '2021', '2021', '2021', '2021', '2021','2022', '2022', '2022', '2022', '2022', '2022', '2022', '2022', '2022', '2022', '2022', '2022','2023', '2023', '2023', '2023', '2023', '2023', '2023', '2023', '2023', '2023', '2023', '2023','2024', '2024', '2024', '2024', '2024', '2024', '2024', '2024', '2024', '2024', '2024', '2024','2025', '2025', '2025', '2025', '2025', '2025', '2025', '2025', '2025', '2025', '2025', '2025','2026']
# creamos el dataframe
df_Cafe = pd.DataFrame(
    {
        "año": año
    }
)
df_Cafe
# Importamos los archivos desde el github que contienen los diferentes datos
url = "https://raw.githubusercontent.com/LeidyDahian/analitica-precio-del-cafe/refs/heads/main/DOLLARINDEX.csv"
df = pd.read_csv(url)
url2 = "https://raw.githubusercontent.com/LeidyDahian/analitica-precio-del-cafe/refs/heads/main/BRENT.csv"
df2 = pd.read_csv(url2)
url3 = "https://raw.githubusercontent.com/LeidyDahian/analitica-precio-del-cafe/refs/heads/main/Costo%20de%20produccion.csv"
df3 = pd.read_csv(url3)
url4 = "https://raw.githubusercontent.com/LeidyDahian/analitica-precio-del-cafe/refs/heads/main/COFFEE.csv"
df4 = pd.read_csv(url4)
df_final_Cafe = pd.concat([df_Cafe, df], axis=1)
df_final_Cafe = pd.merge(df_final_Cafe, df2)
df_final_Cafe = pd.merge(df_final_Cafe, df3)
df_final_Cafe = pd.merge(df_final_Cafe, df4)
# Calculo volatilidad
def rendimiento(df_final_Cafe):
    df_final_Cafe["Rendimiento"] =  (df_final_Cafe["precio_cafe"].shift(-1) - df_final_Cafe["precio_cafe"])/ df_final_Cafe["precio_cafe"]
    return df_final_Cafe
df_final_Cafe = rendimiento(df_final_Cafe)
df_final_Cafe['Promedio rendimiento'] = df_final_Cafe.groupby('año')['Rendimiento'].transform('mean')

def calcular_diferencia_r(df_final_Cafe):
    df_final_Cafe["Diferencia cuadrado"] = (df_final_Cafe["Rendimiento"]-df_final_Cafe['Promedio rendimiento'])**2
    return df_final_Cafe

# Calculamos la nueva columna
df_final_Cafe = calcular_diferencia_r(df_final_Cafe)
df_final_Cafe['Suma diferencia cuadrados'] = df_final_Cafe.groupby('año')['Diferencia cuadrado'].transform('sum')

def volatilidad(df_final_Cafe):
    df_final_Cafe["Volatilidad"] = np.sqrt((df_final_Cafe['Suma diferencia cuadrados'])/11)
    return df_final_Cafe

# Calculamos la nueva columna
df_final_Cafe = volatilidad(df_final_Cafe)

#Depuración columnas
df_Cafe = df_final_Cafe[["año","fecha","indice_dolar","precio_petroleo","costo_produccion_cafe","precio_cafe","Volatilidad"]]
df_Cafe

#Exportación formato excel
#df_Cafe.to_csv('datos_cafe.csv', index=False)
#files.download('datos_cafe.csv')

"""# Identificacion y tratamiento de datos duplicados"""

duplicados = df_Cafe.duplicated()
duplicados_ = duplicados.sum()
duplicados
print(f'Hay {duplicados_} filas duplicadas')

# Revisar duplicados de fecha
duplicados2 = df_Cafe.duplicated(subset=['fecha'],keep=False)
duplicados2_=duplicados2.sum()
print(duplicados2)
print(f'Hay {duplicados2_} fechas duplicadas')

#Revisar que si hayan 12 meses por año
conteo_meses=df_Cafe.groupby('año')['fecha'].count()
conteo_meses

"""# Identificación y tratamiento de datos faltantes"""

df_Cafe.info()

# Identificación si hay valores de 0
dato_cero= df_Cafe[(df_Cafe == 0).any(axis=1)]
dato_cero

df_Cafe = df_Cafe.drop(dato_cero.index)
#Comprobamos la no presencia de la ultima fila
df_Cafe

"""# Categorización y justificación"""

df_Cafe["fecha"] = pd.to_datetime(df_Cafe["fecha"])
df_Cafe["mes"] = df_Cafe["fecha"].dt.month
df_Cafe.head(15)

promedio_mensual = df_Cafe.groupby("mes")["precio_cafe"].mean()
promedio_mensual

df_Cafe[["indice_dolar","precio_petroleo","costo_produccion_cafe","precio_cafe","Volatilidad"]].describe()

"""# 1 Pregunta"""

import plotly.express as px

# 1. Agrupamos por año para tener un solo dato de volatilidad por periodo
df_evolucion_anual = df_Cafe.groupby('año')['Volatilidad'].mean().reset_index()

# 2. Creamos la serie de tiempo anual
fig1 = px.line(df_evolucion_anual,
               x="año",
               y="Volatilidad",
               title="<b>Evolución Anual de la Inestabilidad del Café</b>",
               markers=True,
               labels={"año": "Año", "Volatilidad": "Nivel de Inestabilidad"},
               template="plotly_white")

# Personalización estética
fig1.update_traces(line_color='#8B4513', line_width=3, marker=dict(size=8))
fig1.update_layout(xaxis_type='category') # Para que cada año se vea claramente en el eje
fig1.show()

"""# 2 Pregunta"""

import plotly.graph_objects as go

# 1. Calculamos la media móvil de 12 meses (para ver la tendencia anualizada)
df_Cafe['media_movil_12'] = df_Cafe['precio_cafe'].rolling(window=12).mean()

# 2. Usamos graph_objects para superponer las dos líneas de forma profesional
fig3 = go.Figure()

# Línea del precio real (más clara y delgada para que no sature)
fig3.add_trace(go.Scatter(x=df_Cafe['fecha'], y=df_Cafe['precio_cafe'],
                    mode='lines', name='Precio Mensual',
                    line=dict(color='rgba(139, 69, 19, 0.3)', width=1)))

# Línea de la Media Móvil (más gruesa y oscura para resaltar la tendencia)
fig3.add_trace(go.Scatter(x=df_Cafe['fecha'], y=df_Cafe['media_movil_12'],
                    mode='lines', name='Tendencia (Media 12 meses)',
                    line=dict(color='#5D4037', width=4)))

fig3.update_layout(
    title="<b>Tendencia del Precio del Café con Media Móvil</b>",
    xaxis_title="Año",
    yaxis_title="Precio (USD)",
    template="plotly_white",
    legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1)
)

fig3.show()

# 1. Calculamos promedios
df_mes_promedio = df_Cafe.groupby('mes')['precio_cafe'].mean().reset_index()
meses_map = {1:'Ene', 2:'Feb', 3:'Mar', 4:'Abr', 5:'May', 6:'Jun',
             7:'Jul', 8:'Ago', 9:'Sep', 10:'Oct', 11:'Nov', 12:'Dic'}
df_mes_promedio['nombre_mes'] = df_mes_promedio['mes'].map(meses_map)
promedio_total = df_Cafe['precio_cafe'].mean()

# 2. Creamos el gráfico
fig4 = px.bar(df_mes_promedio,
                  x='nombre_mes',
                  y='precio_cafe',
                 title="<b>¿Existen meses con precios más altos?</b><br><sup>Promedio histórico mensual del precio del café</sup>",
                  labels={'nombre_mes': 'Mes', 'precio_cafe': 'Precio Promedio del cafe (USD)'},
                  text_auto='.2f',
                  template='plotly_white')

# 3. Añadimos la línea SIN texto (para que no se encime)
fig4.add_hline(y=promedio_total, line_dash="dash", line_color="red")

# 4. Añadimos el texto manualmente en una posición segura (fuera de las barras)
fig4.add_annotation(
    x=1.02, # Lo mueve ligeramente a la derecha, fuera del cuadro
    y=promedio_total,
    xref="paper", # Usa coordenadas del papel (0 a 1) para x
    yref="y",     # Usa coordenadas de los datos para y
    text=f"Promedio:<br>{promedio_total:.2f}",
    showarrow=False,
    font=dict(color="red", size=11),
    align="left",
    xanchor="left"
)

# 5. Ajustes finales de espacio
fig4.update_traces(marker_color='#8D6E63', textposition='outside')
fig4.update_layout(
    margin=dict(r=100, l=50, t=80, b=50), # Espacio a la derecha para la anotación
    yaxis=dict(range=[df_mes_promedio['precio_cafe'].min()*0.7,
                     df_mes_promedio['precio_cafe'].max()*1.3]),
    height=450
)

fig4.show()

"""# 3 Pregunta"""

import plotly.graph_objects as go
import pandas as pd

# 1. Preparación de datos limpia
nombres_limpios = {
    "precio_cafe": "Precio del Café",
    "indice_dolar": "Índice del Dólar (DXY)",
    "precio_petroleo": "Precio del Petróleo",
    "costo_produccion_cafe": "Costo de la Producción del Café"
}

# Filtramos y calculamos la correlación
df_sub = df_Cafe[list(nombres_limpios.keys())].dropna()
matriz_corr = df_sub.corr()

# Extraemos etiquetas y valores por separado para evitar errores de Plotly
labels = [nombres_limpios[col] for col in matriz_corr.columns]
valores = matriz_corr.values

# 2. Usamos graph_objects (go.Heatmap) para mayor control de los ejes
fig6 = go.Figure(data=go.Heatmap(
    z=valores,
    x=labels,
    y=labels,
    colorscale='RdBu_r',
    zmin=-1, zmax=1,
    text=valores.round(2), # Texto que aparecerá al pasar el mouse
    texttemplate="%{text}", # Muestra el número dentro del cuadro
    showscale=True
))
# 3. Ajustes de diseño para evitar que los nombres se monten
fig6.update_layout(
    title="<b>Análisis de Influencia Económica</b>",
    width=900,
    height=750,
    template="plotly_white",
    # El margen 'l' (izquierdo) es clave para que los nombres del eje Y no toquen el cuadro
    margin=dict(l=250, r=50, t=100, b=150),

    xaxis=dict(
        tickangle=-45,
        side="bottom"
    ),

    yaxis=dict(
        # Automargin=False y un margen izquierdo grande separan los nombres
        automargin=True,
        # Invertimos el eje para que la diagonal de 1s empiece arriba a la izquierda
        autorange='reversed'
    )
)

# Truco final: añadir espacios al final de los nombres del eje Y para alejarlos físicamente
fig6.update_yaxes(ticksuffix="      ")


fig6.show()

"""# DASHBOARD"""



# ─────────────────────────────────────────────────────────────
# 2. FIGURAS ESTÁTICAS
# ─────────────────────────────────────────────────────────────

CAFE_DARK   = "#3E1C00"
CAFE_MED    = "#6F4E37"
CAFE_LIGHT  = "#A0785A"
CREMA       = "#FDF6EC"
CREMA_DARK  = "#F0E0C0"
GOLD        = "#C8903A"

TEMPLATE = dict(
    layout=go.Layout(
        paper_bgcolor=CREMA,
        plot_bgcolor="#FFF9F2",
        font=dict(
            family="Georgia, serif",
            color=CAFE_DARK
        ),
        title=dict(
            font=dict(
                size=17,
                color=CAFE_DARK
            )
        ),
        xaxis=dict(
            gridcolor="#E8D5B7",
            linecolor="#C8B08A",
            tickfont=dict(color=CAFE_MED)
        ),
        yaxis=dict(
            gridcolor="#E8D5B7",
            linecolor="#C8B08A",
            tickfont=dict(color=CAFE_MED)
        ),
    )
)

# ─────────────────────────────────────────────────────────────
# GRÁFICO 1 — VOLATILIDAD
# ─────────────────────────────────────────────────────────────

df_anual = df_Cafe.groupby('año')['Volatilidad'].mean().reset_index()

fig1 = px.line(
    df_anual,
    x="año",
    y="Volatilidad",
    title="<b>Evolución Anual de la Inestabilidad del Café</b>",
    markers=True,
    labels={
        "año": "Año",
        "Volatilidad": "Nivel de Inestabilidad"
    }
)

fig1.update_traces(
    line_color=CAFE_MED,
    line_width=4,
    marker=dict(
        size=10,
        color=GOLD,
        line=dict(color=CAFE_DARK, width=2)
    )
)

for año, color, texto in [
    (2014, "#B22222", "Pico histórico"),
    (2017, "#2E7D32", "Mínima volatilidad"),
    (2021, "#2E7D32", "Mercado estable")
]:

    fila = df_anual[df_anual["año"] == año]

    fig1.add_scatter(
        x=fila["año"],
        y=fila["Volatilidad"],
        mode='markers+text',
        text=[texto],
        textposition="top center",
        marker=dict(
            size=18,
            color=color,
            line=dict(color="white", width=2)
        ),
        showlegend=False
    )

    fig1.add_vline(
        x=año,
        line_dash="dot",
        line_color=color,
        opacity=0.4
    )

fig1.update_layout(
    height=620,

    paper_bgcolor='#F5E9D8',
    plot_bgcolor='#FFF9F2',

    font=dict(
        family='Georgia',
        color='#4B3621'
    ),

    title=dict(
        x=0.5,
        font=dict(size=22)
    ),

    hovermode='x unified',

    margin=dict(
        l=60,
        r=40,
        t=90,
        b=90
    ),

    xaxis=dict(
        type='linear',
        tickmode='linear',
        dtick=2,
        tickangle=-45,
        showgrid=False
    ),

    yaxis=dict(
        title='Nivel de Inestabilidad (%)',
        gridcolor='rgba(0,0,0,0.08)',
        zeroline=False
    )
)

# ─────────────────────────────────────────────────────────────
# GRÁFICO 2 — TENDENCIA
# ─────────────────────────────────────────────────────────────

fig3 = go.Figure()

fig3.add_trace(go.Scatter(
    x=df_Cafe['fecha'],
    y=df_Cafe['precio_cafe'],
    mode='lines',
    name='Precio Mensual',
    line=dict(
        color='rgba(111,78,55,0.25)',
        width=1
    )
))

fig3.add_trace(go.Scatter(
    x=df_Cafe['fecha'],
    y=df_Cafe['media_movil_12'],
    mode='lines',
    name='Tendencia (Media 12 meses)',
    line=dict(
        color=CAFE_DARK,
        width=3
    )
))

fig3.update_layout(
    title="<b>Tendencia del Precio del Café</b>",
    xaxis_title="Fecha",
    yaxis_title="Precio (USD/libra)",

    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=1.02,
        xanchor="right",
        x=1,
        bgcolor="rgba(253,246,236,0.8)"
    ),

    height=420,

    margin=dict(
        l=50,
        r=30,
        t=70,
        b=50
    ),
)

# ─────────────────────────────────────────────────────────────
# GRÁFICO 3 — BARRAS MENSUALES
# ─────────────────────────────────────────────────────────────

meses_map = {
    1:'Ene',2:'Feb',3:'Mar',4:'Abr',5:'May',6:'Jun',
    7:'Jul',8:'Ago',9:'Sep',10:'Oct',11:'Nov',12:'Dic'
}

df_mes = df_Cafe.groupby('mes')['precio_cafe'].mean().reset_index()

df_mes['nombre_mes'] = df_mes['mes'].map(meses_map)

promedio_total = df_Cafe['precio_cafe'].mean()

fig4 = px.bar(
    df_mes,
    x='nombre_mes',
    y='precio_cafe',

    title="<b>¿Existen meses con precios más altos?</b><br><sup>Promedio histórico mensual</sup>",

    labels={
        'nombre_mes': 'Mes',
        'precio_cafe': 'Precio Promedio (USD/libra)'
    },

    text_auto='.1f',
)

fig4.update_traces(
    marker_color=CAFE_LIGHT,
    textposition='outside',
    marker_line_color=CAFE_DARK,
    marker_line_width=1
)

fig4.add_hline(
    y=promedio_total,
    line_dash="dash",
    line_color=GOLD,
    line_width=2
)

fig4.add_annotation(
    x=1.02,
    y=promedio_total,
    xref="paper",
    yref="y",

    text=f"Prom:<br>{promedio_total:.1f}",

    showarrow=False,

    font=dict(
        color=GOLD,
        size=11
    ),

    align="left",
    xanchor="left"
)

fig4.update_layout(

    margin=dict(
        r=90,
        l=50,
        t=80,
        b=50
    ),

    yaxis=dict(
        range=[
            df_mes['precio_cafe'].min()*0.7,
            df_mes['precio_cafe'].max()*1.25
        ]
    ),

    height=420,
)

# ─────────────────────────────────────────────────────────────
# MAPA DE CORRELACIÓN
# ─────────────────────────────────────────────────────────────

columnas_corr = {
    'precio_cafe': 'Precio del Café ',
    'indice_dolar': 'Índice del Dólar (DXY) ',
    'precio_petroleo': 'Precio del Petróleo ',
    'costo_produccion_cafe': 'Costo de Producción del Café '
}

correlaciones = df_Cafe[list(columnas_corr.keys())].corr()

# Renombrar filas y columnas
correlaciones.rename(
    index=columnas_corr,
    columns=columnas_corr,
    inplace=True
)

fig6 = px.imshow(

    correlaciones,

    text_auto='.2f',

    color_continuous_scale=[

        [0.0, '#F5E9D8'],
        [0.5, '#C58B45'],
        [1.0, '#4B2E1E']
    ],

    aspect='auto'
)

fig6.update_layout(

    title={
        'text': '<b>Mapa de Correlaciones Económicas</b>',
        'x': 0.5,
        'font': {
            'family': 'Georgia',
            'size': 22,
            'color': '#4B3621'
        }
    },

    paper_bgcolor='#F5E9D8',
    plot_bgcolor='#FFF9F2',

    font=dict(
        family='Georgia',
        color='#4B3621'
    ),

    margin=dict(
        l=40,
        r=40,
        t=80,
        b=40
    ),

    height=500,

    coloraxis_colorbar=dict(
        title='Correlación'
    )
)

fig6.update_xaxes(
    side='bottom'
)

fig6.update_traces(

    hovertemplate=
        "<b>%{x}</b> vs <b>%{y}</b><br>" +
        "Correlación: %{z:.2f}<extra></extra>"
)

# ─────────────────────────────────────────────────────────────
# FUNCIÓN — GRÁFICO DISPERSIÓN
# ─────────────────────────────────────────────────────────────

def generar_dispersion(df_Cafe, variable):

    config = {

        'costo_produccion_cafe': {
            'titulo': 'Costo de Producción del Café',
            'color': '#2E7D32',
        },

        'indice_dolar': {
            'titulo': 'Índice del Dólar (DXY)',
            'color': '#C58B45',
        },

        'precio_petroleo': {
            'titulo': 'Precio del Petróleo',
            'color': '#8B5A2B',
        },
    }

    c = config[variable]

    fig = px.scatter(

        df_Cafe,

        x=variable,
        y='precio_cafe',

        trendline='ols',

        title=f"<b>Relación entre {c['titulo']} y el Precio del Café</b>",

        color_discrete_sequence=[c['color']]
    )

    fig.update_traces(

        marker=dict(
            size=9,
            opacity=0.75,

            line=dict(
                width=1,
                color='white'
            )
        ),

        hovertemplate=
            "<b>Variable:</b> %{x:.2f}<br>" +
            "<b>Precio Café:</b> %{y:.2f}<extra></extra>"
    )

    if len(fig.data) > 1:

        fig.data[1].update(

            line=dict(
                color='#B22222',
                width=4,
                dash='dot'
            )
        )

    fig.update_layout(

        height=560,

        paper_bgcolor='#F5E9D8',
        plot_bgcolor='#FFF9F2',

        font=dict(
            family='Georgia',
            color='#4B3621'
        ),

        title=dict(
            x=0.5,
            font=dict(size=22)
        ),

        hovermode='closest',

        margin=dict(
            l=60,
            r=40,
            t=80,
            b=70
        ),

        xaxis=dict(
            title=c['titulo'],
            showgrid=False
        ),

        yaxis=dict(
            title='Precio del Café',
            gridcolor='rgba(0,0,0,0.08)',
            zeroline=False
        )
    )

    return fig

ESTILO_HEADER = {
    'background': f'linear-gradient(135deg, {CAFE_DARK} 0%, {CAFE_MED} 60%, {GOLD} 100%)',
    'padding': '32px 24px 28px',
    'marginBottom': '0',
}

ESTILO_TAB_SELECCIONADO = {
    'backgroundColor': CAFE_MED,
    'color': CREMA,
    'fontWeight': 'bold',
    'borderTop': f'3px solid {GOLD}',
    'border': 'none',
    'padding': '12px 24px',
    'fontFamily': 'Georgia, serif',
    'fontSize': '14px',
    'borderRadius': '6px 6px 0 0',
}

ESTILO_TAB = {
    'backgroundColor': CREMA_DARK,
    'color': CAFE_MED,
    'border': 'none',
    'padding': '12px 24px',
    'fontFamily': 'Georgia, serif',
    'fontSize': '14px',
    'borderRadius': '6px 6px 0 0',
}

ESTILO_CONTENEDOR = {
    'backgroundColor': CREMA,
    'border': f'1px solid {CAFE_LIGHT}',
    'borderRadius': '0 8px 8px 8px',
    'padding': '24px',
    'boxShadow': '0 4px 16px rgba(62,28,0,0.10)',
}

ESTILO_H3 = {
    'color': CAFE_DARK,
    'fontFamily': 'Georgia, serif',
    'fontWeight': 'bold',
    'borderLeft': f'5px solid {GOLD}',
    'paddingLeft': '14px',
    'marginBottom': '20px',
}

ESTILO_DROPDOWN = {
    'fontFamily': 'Georgia, serif',
    'color': CAFE_DARK,
    'backgroundColor': CREMA,
    'border': f'1px solid {CAFE_LIGHT}',
    'borderRadius': '6px',
}

# ─────────────────────────────────────────────────────────────
# 6. APP & LAYOUT
# ─────────────────────────────────────────────────────────────

app = Dash(
    __name__,
    external_stylesheets=[dbc.themes.BOOTSTRAP],
    suppress_callback_exceptions=True
)

app.layout = html.Div(

    style={
        'backgroundColor': '#2B1500',
        'minHeight': '100vh'
    },

    children=[

        # ── HEADER ──────────────────────────────────────────
        html.Div(

            style=ESTILO_HEADER,

            children=[

                html.H1(
                    "Análisis del Precio Internacional del Café",

                    style={
                        'color': CREMA,
                        'fontFamily': 'Georgia, serif',
                        'fontWeight': 'bold',
                        'textAlign': 'center',
                        'margin': 0,
                        'letterSpacing': '1px',
                        'fontSize': '1.9rem'
                    }
                ),

                html.P(
                    "Evolución histórica 2006–2025 · Variables económicas y volatilidad",

                    style={
                        'color': CREMA_DARK,
                        'textAlign': 'center',
                        'margin': '8px 0 0',
                        'fontSize': '0.95rem',
                        'fontFamily': 'Georgia, serif',
                        'opacity': '0.85'
                    }
                ),
            ]
        ),

        # ── CONTENIDO PRINCIPAL ────────────────────────────
        dbc.Container(

            fluid=True,

            style={
                'paddingTop': '28px',
                'paddingBottom': '40px',
                'maxWidth': '1300px'
            },

            children=[

                html.Div(
                    style={
                        'height': '4px',
                        'background': f'linear-gradient(90deg, {GOLD}, {CAFE_MED}, {GOLD})',
                        'borderRadius': '2px',
                        'marginBottom': '24px'
                    }
                ),

                # ── TABS ───────────────────────────────────
                dcc.Tabs(
                    id="tabs-preguntas",
                    value='tab-1',

                    style={'border': 'none'},

                    colors={
                        "border": CREMA,
                        "primary": GOLD,
                        "background": CREMA_DARK
                    },

                    children=[

                        dcc.Tab(
                            label='Pregunta 1 — Volatilidad',
                            value='tab-1',
                            style=ESTILO_TAB,
                            selected_style=ESTILO_TAB_SELECCIONADO
                        ),

                        dcc.Tab(
                            label='Pregunta 2 — Tendencias',
                            value='tab-2',
                            style=ESTILO_TAB,
                            selected_style=ESTILO_TAB_SELECCIONADO
                        ),

                        dcc.Tab(
                            label='Pregunta 3 — Dispersión',
                            value='tab-3',
                            style=ESTILO_TAB,
                            selected_style=ESTILO_TAB_SELECCIONADO
                        ),
                    ]
                ),

                html.Div(
                    id='contenido-tabs',
                    style=ESTILO_CONTENEDOR
                ),

            ]
        ),
    ]
)


# ─────────────────────────────────────────────────────────────
# TARJETAS DINÁMICAS POR AÑO
# ─────────────────────────────────────────────────────────────

def tarjeta_anual(año):

    datos = {

        2014: {
            "titulo": "2014",
            "subtitulo": "Punto más alto",
            "volatilidad": "12.32%",
            "color": "#B22222",
            "icono": "📈",

            "pregunta": "¿Por qué la volatilidad se disparó en 2014?",

            "bullets": [
                "Sequía severa en Brasil: la peor en décadas redujo drásticamente la producción de café arábica.",
                "Heladas y estrés climático en Minas Gerais y São Paulo aumentaron la incertidumbre global.",
                "Fuerte especulación financiera en mercados de commodities agrícolas.",
                "Caída de inventarios certificados y temor de escasez mundial.",
                "Demanda internacional sólida mientras la oferta se contraía.",
                "La apreciación del dólar y el incremento en costos energéticos y logísticos amplificaron la volatilidad del mercado cafetero."
            ],

            "referencias": [
                "ICO — Coffee Market Report 2014",
                "USDA — Coffee: World Markets and Trade (2014)",
                "Reuters — Brazil drought drives coffee prices higher"
            ],

            "conclusion":
                "Choques simultáneos de oferta + especulación financiera provocaron "
                "el mayor pico de volatilidad de toda la serie."
        },

        2017: {
            "titulo": "2017",
            "subtitulo": "Punto más bajo",
            "volatilidad": "2.61%",
            "color": "#2E7D32",
            "icono": "📉",

            "pregunta": "¿Por qué la volatilidad fue tan baja en 2017?",

            "bullets": [
                "Excelentes condiciones climáticas en Brasil y Vietnam.",
                "Producción récord y recuperación de inventarios globales.",
                "Mercado internacional más estable y predecible.",
                "Menor presión especulativa en commodities agrícolas.",
                "Oferta abundante frente a un crecimiento moderado de la demanda.",
                "Estabilidad relativa del dólar y menores presiones en costos energéticos ayudaron a reducir la incertidumbre del mercado."
            ],

            "referencias": [
                "ICO — Coffee Market Report 2017",
                "USDA — Coffee: World Markets and Trade (2017)",
                "CEPEA/ESALQ — Reporte cafetalero 2017"
            ],

            "conclusion":
                "La abundancia de oferta y un entorno macroeconómico estable "
                "redujeron considerablemente la incertidumbre."
        },

        2021: {
            "titulo": "2021",
            "subtitulo": "Punto más bajo",
            "volatilidad": "2.92%",
            "color": "#2E7D32",
            "icono": "📉",

            "pregunta": "¿Por qué la volatilidad fue tan baja en 2021?",

            "bullets": [
                "Normalización gradual de cadenas logísticas internacionales.",
                "Mayor estabilidad cambiaria frente a años anteriores.",
                "Producción relativamente estable en países exportadores.",
                "Mercado más adaptado al contexto post-pandemia.",
                "Recuperación de inventarios y menor incertidumbre financiera.",
                "Mayor equilibrio en variables macroeconómicas como petróleo, dólar y costos de producción favoreció una volatilidad más moderada."
            ],

            "referencias": [
                "ICO — Coffee Market Report 2021",
                "World Bank — Commodity Markets Outlook",
                "USDA — Coffee: World Markets and Trade (2021)"
            ],

            "conclusion":
                "El equilibrio entre oferta, demanda y logística internacional "
                "generó un periodo de menor inestabilidad."
        }
    }

    d = datos[año]

    return html.Div([

        # ── HEADER ──────────────────────────────────────
        html.Div([

            html.Div(
                d["icono"],

                style={
                    'fontSize': '38px',
                    'marginRight': '16px'
                }
            ),

            html.Div([

                html.H2(
                    d["titulo"],

                    style={
                        'margin': '0',
                        'color': d["color"],
                        'fontFamily': 'Georgia, serif',
                        'fontWeight': 'bold'
                    }
                ),

                html.H5(
                    d["subtitulo"],

                    style={
                        'margin': '0',
                        'color': d["color"],
                        'fontFamily': 'Georgia, serif'
                    }
                ),

                html.H4(
                    d["volatilidad"],

                    style={
                        'marginTop': '4px',
                        'color': d["color"],
                        'fontWeight': 'bold'
                    }
                ),

            ])

        ], style={
            'display': 'flex',
            'alignItems': 'center',
            'marginBottom': '18px'
        }),

        html.Hr(style={
            'borderColor': d["color"]
        }),

        # ── PREGUNTA ────────────────────────────────────
        html.H4(
            d["pregunta"],

            style={
                'color': d["color"],
                'fontFamily': 'Georgia, serif',
                'fontWeight': 'bold',
                'marginBottom': '20px',
                'lineHeight': '1.4'
            }
        ),

        # ── BULLETS ─────────────────────────────────────
        html.Ul([

            html.Li(
                b,

                style={
                    'marginBottom': '14px',
                    'color': '#4B3621',
                    'fontSize': '15px',
                    'lineHeight': '1.6'
                }
            )

            for b in d["bullets"]

        ], style={
            'paddingLeft': '20px',
            'fontFamily': 'Georgia, serif'
        }),

        # ── REFERENCIAS ─────────────────────────────────
        html.Div([

            html.H6(
                "Referencias:",

                style={
                    'color': d["color"],
                    'fontWeight': 'bold',
                    'marginTop': '24px'
                }
            ),

            html.Ul([

                html.Li(
                    r,

                    style={
                        'fontSize': '12px',
                        'color': '#6B4F3A',
                        'marginBottom': '4px'
                    }
                )

                for r in d["referencias"]

            ])

        ]),

        # ── CONCLUSIÓN ──────────────────────────────────
        html.Div(

            d["conclusion"],

            style={
                'marginTop': '20px',
                'backgroundColor': '#F8F1E7',
                'padding': '14px',
                'borderRadius': '10px',
                'borderLeft': f'5px solid {d["color"]}',
                'fontWeight': 'bold',
                'color': d["color"],
                'lineHeight': '1.5',
                'fontSize': '14px'
            }
        )

    ], style={

        'backgroundColor': '#F5E9D8',
        'padding': '24px',
        'borderRadius': '18px',
        'border': f'2px solid {d["color"]}',
        'boxShadow': '0 6px 18px rgba(0,0,0,0.12)',
        'height': '100%'

    })


# ─────────────────────────────────────────────────────────────
# 7. CALLBACKS
# ─────────────────────────────────────────────────────────────

@app.callback(
    Output('contenido-tabs', 'children'),
    Input('tabs-preguntas', 'value')
)
def renderizar_contenido(tab):

    # ─────────────────────────────────────────────────────
    # PESTAÑA 1 — VOLATILIDAD
    # ─────────────────────────────────────────────────────
    if tab == 'tab-1':

        return html.Div([

            html.H3(
                "¿Cómo ha evolucionado la volatilidad del precio del café?",
                style=ESTILO_H3
            ),

            dbc.Row([

                # ── GRÁFICO ───────────────────────────
                dbc.Col([

                    dcc.Graph(
                        figure=fig1,
                        config={'displayModeBar': False}
                    ),

                ], width=8),

                # ── PANEL DERECHO ────────────────────
                dbc.Col([

                    html.H5(
                        "Explorar un año específico",

                        style={
                            'color': CAFE_DARK,
                            'fontFamily': 'Georgia, serif',
                            'marginBottom': '18px',
                            'fontWeight': 'bold'
                        }
                    ),

                    dbc.Row([

                        dbc.Col(

                            dbc.Button(
                                "2014",
                                id="btn-2014",
                                size="sm",

                                style={
                                    'background': '#8B0000',
                                    'border': 'none',
                                    'color': CREMA,
                                    'fontFamily': 'Georgia, serif',
                                    'width': '100%',
                                    'borderRadius': '10px',
                                    'fontWeight': 'bold',
                                    'padding': '10px',
                                    'boxShadow': '0 3px 8px rgba(0,0,0,0.2)'
                                }
                            )
                        ),

                        dbc.Col(

                            dbc.Button(
                                "2017",
                                id="btn-2017",
                                size="sm",

                                style={
                                    'background': '#2E7D32',
                                    'border': 'none',
                                    'color': CREMA,
                                    'fontFamily': 'Georgia, serif',
                                    'width': '100%',
                                    'borderRadius': '10px',
                                    'fontWeight': 'bold',
                                    'padding': '10px',
                                    'boxShadow': '0 3px 8px rgba(0,0,0,0.2)'
                                }
                            )
                        ),

                        dbc.Col(

                            dbc.Button(
                                "2021",
                                id="btn-2021",
                                size="sm",

                                style={
                                    'background': '#2E7D32',
                                    'border': 'none',
                                    'color': CREMA,
                                    'fontFamily': 'Georgia, serif',
                                    'width': '100%',
                                    'borderRadius': '10px',
                                    'fontWeight': 'bold',
                                    'padding': '10px',
                                    'boxShadow': '0 3px 8px rgba(0,0,0,0.2)'
                                }
                            )
                        ),

                    ], className="mb-4 g-2"),

                    html.Div(
                        id='informacion-anual',
                        children=tarjeta_anual(2014)
                    ),

                ], width=4),

            ]),

        ])

    # ─────────────────────────────────────────────────────
    # PESTAÑA 2 — TENDENCIAS
    # ─────────────────────────────────────────────────────
    elif tab == 'tab-2':

        return html.Div([

            # ── TÍTULO ───────────────────────────────
            html.H3(
                "¿Existen tendencias o patrones en el precio del café?",
                style=ESTILO_H3
            ),

            # ── GRÁFICOS ─────────────────────────────
            dbc.Row([

                dbc.Col(

                    dcc.Graph(
                        figure=fig3,
                        config={'displayModeBar': False}
                    ),

                    width=6
                ),

                dbc.Col(

                    dcc.Graph(
                        figure=fig4,
                        config={'displayModeBar': False}
                    ),

                    width=6
                ),

            ]),

            html.Br(),

            # ── PANEL STORYTELLING ───────────────────
            html.Div([

                html.H4(
                    "Interpretación de las tendencias observadas",

                    style={
                        'color': CAFE_DARK,
                        'fontFamily': 'Georgia, serif',
                        'fontWeight': 'bold',
                        'marginBottom': '18px'
                    }
                ),

                html.P(
                    "El comportamiento histórico del precio internacional "
                    "del café evidencia que el mercado no se mueve de forma "
                    "completamente aleatoria. Entre 2006 y 2025 se observan "
                    "ciclos de crecimiento, correcciones y periodos de estabilidad "
                    "influenciados por factores climáticos, económicos y logísticos.",

                    style={
                        'fontSize': '15px',
                        'lineHeight': '1.8',
                        'color': '#4B3621',
                        'fontFamily': 'Georgia, serif'
                    }
                ),

                html.P(
                    "La media móvil de 12 meses permite identificar tendencias "
                    "estructurales de largo plazo, suavizando fluctuaciones "
                    "temporales y revelando periodos donde el precio del café "
                    "aumentó de manera sostenida, especialmente después de "
                    "eventos climáticos severos o incrementos en los costos "
                    "de producción.",

                    style={
                        'fontSize': '15px',
                        'lineHeight': '1.8',
                        'color': '#4B3621',
                        'fontFamily': 'Georgia, serif'
                    }
                ),

                html.P(
                    "El análisis mensual también evidencia patrones "
                    "estacionales moderados. Históricamente, los precios "
                    "promedio tienden a ser más altos entre septiembre "
                    "y diciembre, mientras que los primeros meses del año "
                    "presentan un comportamiento relativamente más estable. "
                    "Esto puede estar asociado a ciclos de cosecha, "
                    "niveles de inventario, exportaciones y expectativas "
                    "del mercado cafetero internacional.",

                    style={
                        'fontSize': '15px',
                        'lineHeight': '1.8',
                        'color': '#4B3621',
                        'fontFamily': 'Georgia, serif'
                    }
                ),

                # ── HALLAZGOS ────────────────────────
                html.Div([

                    html.H5(
                        "Hallazgos clave",

                        style={
                            'color': GOLD,
                            'fontWeight': 'bold',
                            'fontFamily': 'Georgia, serif',
                            'marginBottom': '14px'
                        }
                    ),

                    html.Ul([

                        html.Li(
                            "El precio del café presenta ciclos de largo plazo claramente identificables.",

                            style={
                                'marginBottom': '10px',
                                'lineHeight': '1.6'
                            }
                        ),

                        html.Li(
                            "Los eventos climáticos extremos generan cambios estructurales en la tendencia.",

                            style={
                                'marginBottom': '10px',
                                'lineHeight': '1.6'
                            }
                        ),

                        html.Li(
                            "Variables macroeconómicas como el dólar, el petróleo y los costos de producción amplifican los movimientos del mercado.",

                            style={
                                'marginBottom': '10px',
                                'lineHeight': '1.6'
                            }
                        ),

                        html.Li(
                            "Existe evidencia de patrones estacionales moderados en determinados meses del año.",

                            style={
                                'marginBottom': '10px',
                                'lineHeight': '1.6'
                            }
                        ),

                    ], style={
                        'paddingLeft': '20px',
                        'color': '#4B3621',
                        'fontFamily': 'Georgia, serif',
                        'fontSize': '15px'
                    })

                ], style={
                    'marginTop': '20px'
                }),

                # ── CONCLUSIÓN ───────────────────────
                html.Div(

                    "Conclusión: el mercado cafetero sí presenta tendencias "
                    "y patrones identificables. El comportamiento del precio "
                    "internacional del café está influenciado por dinámicas "
                    "de oferta y demanda, factores climáticos y variables "
                    "macroeconómicas que afectan el mercado a lo largo del tiempo.",

                    style={
                        'marginTop': '24px',
                        'backgroundColor': '#F8F1E7',
                        'padding': '16px',
                        'borderRadius': '10px',
                        'borderLeft': f'5px solid {GOLD}',
                        'fontWeight': 'bold',
                        'color': CAFE_DARK,
                        'lineHeight': '1.6',
                        'fontSize': '14px'
                    }
                )

            ], style={

                'backgroundColor': '#F5E9D8',
                'padding': '24px',
                'borderRadius': '16px',
                'border': f'1px solid {CAFE_LIGHT}',
                'marginTop': '20px',
                'boxShadow': '0 4px 14px rgba(0,0,0,0.10)'

            })

        ])

# ─────────────────────────────────────────────────────────────
# ── PESTAÑA 3 ────────────────────────────────────────────────
# ─────────────────────────────────────────────────────────────

    elif tab == 'tab-3':

        return html.Div([

            # ─────────────────────────────────────────────
            # TÍTULO
            # ─────────────────────────────────────────────
            html.H3(
                "Relación entre variables económicas y el precio del café",
                style=ESTILO_H3
            ),

            # ─────────────────────────────────────────────
            # FILA SUPERIOR
            # ─────────────────────────────────────────────
            dbc.Row([

                # ─────────────────────────────────────────
                # COLUMNA IZQUIERDA — DISPERSIÓN
                # ─────────────────────────────────────────
                dbc.Col([

                    html.Div([

                        html.Label(
                            "Seleccione la variable económica:",

                            style={
                                'fontWeight': 'bold',
                                'color': CAFE_DARK,
                                'fontFamily': 'Georgia, serif',
                                'marginBottom': '6px'
                            }
                        ),

                        dcc.Dropdown(

                            id='dropdown-variables',

                            options=[

                                {
                                    'label': 'Índice del Dólar (DXY)',
                                    'value': 'indice_dolar'
                                },

                                {
                                    'label': 'Precio del Petróleo',
                                    'value': 'precio_petroleo'
                                },

                                {
                                    'label': 'Costo Producción del Café',
                                    'value': 'costo_produccion_cafe'
                                },
                            ],

                            value='indice_dolar',

                            clearable=False,

                            style=ESTILO_DROPDOWN,
                        ),

                    ], style={

                        'padding': '16px',
                        'marginBottom': '16px',
                        'backgroundColor': CREMA_DARK,
                        'borderRadius': '8px',
                        'border': f'1px solid {CAFE_LIGHT}',
                    }),

                    # ─────────────────────────────────────
                    # GRÁFICO DISPERSIÓN
                    # ─────────────────────────────────────
                    dcc.Graph(

                        id='grafico-dispersion-interactivo',

                        style={
                            'height': '560px'
                        },

                        config={
                            'displayModeBar': False
                        },
                    ),

                ], width=8),

                # ─────────────────────────────────────────
                # COLUMNA DERECHA — STORYTELLING
                # ─────────────────────────────────────────
                dbc.Col([

                    html.Div([

                        html.H4(
                            "¿Qué muestran estas relaciones?",

                            style={
                                'color': CAFE_DARK,
                                'fontFamily': 'Georgia, serif',
                                'fontWeight': 'bold',
                                'marginBottom': '14px'
                            }
                        ),

                        html.P(

                            "Cada punto representa un momento histórico del mercado cafetero. "
                            "La línea punteada muestra la tendencia estadística entre la variable "
                            "económica seleccionada y el precio internacional del café.",

                            style={
                                'color': '#4B3621',
                                'fontSize': '14px',
                                'lineHeight': '1.8',
                                'fontFamily': 'Georgia, serif',
                                'marginBottom': '18px'
                            }
                        ),

                        html.Hr(style={
                            'borderColor': '#C8A27A'
                        }),

                        # ─────────────────────────────────
                        # HALLAZGOS
                        # ─────────────────────────────────
                        html.H5(
                            "Hallazgos clave",

                            style={
                                'color': GOLD,
                                'fontFamily': 'Georgia, serif',
                                'fontWeight': 'bold',
                                'marginBottom': '12px'
                            }
                        ),

                        html.Ul([

                            html.Li(
                                "El costo de producción tiene la relación más fuerte "
                                "con el precio del café, lo que demuestra que los costos "
                                "de fertilizantes, transporte y energía afectan directamente "
                                "el mercado cafetero.",

                                style={
                                    'marginBottom': '12px',
                                    'lineHeight': '1.7',
                                    'color': '#4B3621'
                                }
                            ),

                            html.Li(
                                "El índice del dólar influye en el comportamiento "
                                "de los commodities internacionales. Un dólar fuerte "
                                "puede alterar el flujo comercial y la dinámica "
                                "de precios globales.",

                                style={
                                    'marginBottom': '12px',
                                    'lineHeight': '1.7',
                                    'color': '#4B3621'
                                }
                            ),

                            html.Li(
                                "El petróleo tiene una relación menor, pero sigue siendo "
                                "importante porque impacta los costos logísticos y de exportación.",

                                style={
                                    'marginBottom': '12px',
                                    'lineHeight': '1.7',
                                    'color': '#4B3621'
                                }
                            ),

                        ], style={
                            'paddingLeft': '18px',
                            'fontFamily': 'Georgia, serif'
                        }),

                        # ─────────────────────────────────
                        # CONCLUSIÓN
                        # ─────────────────────────────────
                        html.Div(

                            "El comportamiento del café no depende únicamente de la cosecha "
                            "o el clima. Variables macroeconómicas como el dólar, el petróleo "
                            "y los costos de producción también influyen en la estabilidad "
                            "y evolución del precio internacional.",

                            style={
                                'marginTop': '18px',
                                'backgroundColor': '#F8F1E7',
                                'padding': '16px',
                                'borderRadius': '12px',
                                'borderLeft': f'5px solid {GOLD}',
                                'color': '#4B3621',
                                'fontWeight': 'bold',
                                'lineHeight': '1.7',
                                'fontSize': '14px',
                                'fontFamily': 'Georgia, serif'
                            }
                        )

                    ], style={

                        'backgroundColor': '#F5E9D8',
                        'padding': '22px',
                        'borderRadius': '16px',
                        'border': f'1px solid {CAFE_LIGHT}',
                        'boxShadow': '0 4px 12px rgba(0,0,0,0.08)',
                        'height': '100%'
                    })

                ], width=4),

            ], className="mb-4"),

            # ─────────────────────────────────────────────
            # FILA INFERIOR — MAPA DE CALOR
            # ─────────────────────────────────────────────
            dbc.Row([

                # ─────────────────────────────────────────
                # HEATMAP
                # ─────────────────────────────────────────
                dbc.Col(

                    dcc.Graph(
                        figure=fig6,
                        config={'displayModeBar': False}
                    ),

                    width=8
                ),

                # ─────────────────────────────────────────
                # EXPLICACIÓN HEATMAP
                # ─────────────────────────────────────────
                dbc.Col([

                    html.Div([

                        html.H4(
                            "¿Qué revela el mapa de correlación?",

                            style={
                                'color': CAFE_DARK,
                                'fontFamily': 'Georgia, serif',
                                'fontWeight': 'bold',
                                'marginBottom': '16px'
                            }
                        ),

                        html.P(

                            "El mapa de calor permite identificar qué variables "
                            "económicas tienen mayor relación con el precio "
                            "internacional del café. Mientras más intenso es el "
                            "color café, más fuerte es la relación positiva.",

                            style={
                                'color': '#4B3621',
                                'fontSize': '14px',
                                'lineHeight': '1.8',
                                'fontFamily': 'Georgia, serif',
                                'marginBottom': '18px'
                            }
                        ),

                        html.Hr(style={
                            'borderColor': '#C8A27A'
                        }),

                        html.Ul([

                            html.Li(
                                "La correlación más fuerte se observa entre el costo "
                                "de producción y el precio del café (0.86).",

                                style={
                                    'marginBottom': '12px',
                                    'lineHeight': '1.7',
                                    'color': '#4B3621'
                                }
                            ),

                            html.Li(
                                "El dólar mantiene una relación moderada con el mercado cafetero.",

                                style={
                                    'marginBottom': '12px',
                                    'lineHeight': '1.7',
                                    'color': '#4B3621'
                                }
                            ),

                            html.Li(
                                "El petróleo influye indirectamente mediante costos "
                                "energéticos y logísticos.",

                                style={
                                    'marginBottom': '12px',
                                    'lineHeight': '1.7',
                                    'color': '#4B3621'
                                }
                            ),

                            html.Li(
                                "La correlación negativa entre petróleo y dólar "
                                "(-0.50) refleja movimientos macroeconómicos opuestos.",

                                style={
                                    'marginBottom': '12px',
                                    'lineHeight': '1.7',
                                    'color': '#4B3621'
                                }
                            ),

                        ], style={
                            'paddingLeft': '18px',
                            'fontFamily': 'Georgia, serif'
                        }),

                        html.Div(

                            "En conjunto, el análisis demuestra que el precio "
                            "del café está conectado no solo con factores agrícolas, "
                            "sino también con dinámicas financieras y económicas globales.",

                            style={
                                'marginTop': '18px',
                                'backgroundColor': '#F8F1E7',
                                'padding': '16px',
                                'borderRadius': '12px',
                                'borderLeft': f'5px solid {GOLD}',
                                'color': '#4B3621',
                                'fontWeight': 'bold',
                                'lineHeight': '1.7',
                                'fontSize': '14px',
                                'fontFamily': 'Georgia, serif'
                            }
                        )

                    ], style={

                        'backgroundColor': '#F5E9D8',
                        'padding': '22px',
                        'borderRadius': '16px',
                        'border': f'1px solid {CAFE_LIGHT}',
                        'boxShadow': '0 4px 12px rgba(0,0,0,0.08)',
                        'height': '100%'
                    })

                ], width=4),

            ])

        ])
# ─────────────────────────────────────────────────────────────
# CALLBACK DISPERSIÓN
# ─────────────────────────────────────────────────────────────

@app.callback(
    Output('grafico-dispersion-interactivo', 'figure'),
    Input('dropdown-variables', 'value')
)
def actualizar_dispersion(variable):
    return generar_dispersion(df_Cafe, variable)

@app.callback(
    Output('insight-dinamico-dispersion', 'children'),
    Input('dropdown-variables', 'value')
)
def actualizar_insight(variable):

    insights = {

        'indice_dolar':
            "El fortalecimiento del dólar suele aumentar moderadamente "
            "el precio internacional del café debido a efectos cambiarios "
            "y presión sobre exportaciones.",

        'precio_petroleo':
            "El petróleo afecta principalmente costos logísticos, "
            "transporte y producción, aunque su relación directa "
            "con el café es relativamente baja.",

        'costo_produccion_cafe':
            "El costo de producción presenta la relación más fuerte "
            "con el precio del café, evidenciando cómo el aumento "
            "de costos impacta directamente el mercado cafetero."
    }

    return insights[variable]


# ─────────────────────────────────────────────────────────────
# CALLBACK TARJETAS AÑO
# ─────────────────────────────────────────────────────────────

@app.callback(
    Output('informacion-anual', 'children'),
    Input('btn-2014', 'n_clicks'),
    Input('btn-2017', 'n_clicks'),
    Input('btn-2021', 'n_clicks'),
)
def mostrar_info_anual(b2014, b2017, b2021):

    ctx = callback_context
    año = 2014

    if ctx.triggered:

        bid = ctx.triggered[0]['prop_id'].split('.')[0]

        if bid == 'btn-2017':
            año = 2017

        elif bid == 'btn-2021':
            año = 2021

    return tarjeta_anual(año)

server = app.server

if __name__ == "__main__":
    app.run(debug=False)
